// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Voidwell.FileWell.Data;

namespace Voidwell.FileWell.Data.Migrations
{
    [DbContext(typeof(FileDbContext))]
    [Migration("20181030175717_filedbcontext.release.1")]
    partial class filedbcontextrelease1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Voidwell.FileWell.Data.Models.FileRecord", b =>
                {
                    b.Property<Guid>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("file_id");

                    b.Property<Guid?>("DeleteUserId")
                        .HasColumnName("delete_user_id");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnName("deleted_date");

                    b.Property<string>("FileMimeType")
                        .HasColumnName("file_mime_type");

                    b.Property<string>("FileName")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnName("file_size");

                    b.Property<string>("FileType")
                        .HasColumnName("file_type");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnName("is_deleted");

                    b.Property<List<string>>("Tags")
                        .HasColumnName("tags");

                    b.Property<Guid>("UploadUserId")
                        .HasColumnName("upload_user_id");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnName("uploaded_date");

                    b.HasKey("FileId")
                        .HasName("pk_file");

                    b.ToTable("file");
                });
#pragma warning restore 612, 618
        }
    }
}
